# Generated by Django 4.0.1 on 2022-01-12 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('example_payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('SHELLY RGBW2', 'SHELLY RGBW2'), ('IKEA_BULB', 'IKEA_BULB')], max_length=12)),
                ('state', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ActionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('payload_key', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('string', 'string'), ('number', 'number'), ('boolean', 'boolean')], max_length=7)),
                ('operation', models.CharField(choices=[('eq', 'eq'), ('ne', 'ne'), ('lt', 'lt'), ('le', 'le'), ('gt', 'gt'), ('ge', 'ge')], max_length=2)),
                ('payload', models.JSONField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.action')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='action_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.actiondevice'),
        ),
        migrations.AddField(
            model_name='action',
            name='consumer_devices',
            field=models.ManyToManyField(to='demo_app.ConsumerDevice'),
        ),
    ]
