# Generated by Django 4.0.1 on 2022-01-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiondevice',
            name='example_payload',
        ),
    ]
