# Generated by Django 4.0.1 on 2022-01-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_remove_actiondevice_example_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerdevice',
            name='type',
        ),
    ]
