# Generated by Django 4.0.1 on 2022-01-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_remove_consumerdevice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerdevice',
            name='state',
        ),
    ]
